export const CHATBOT_MODULES = [
  {
    key: "orders",
    label: "Orders",
    endpoint: "orders/chatbot",
    questions: [
      { label: "Show all orders", value: "show all orders" },
      { label: "Show pending orders", value: "show pending orders" },
      { label: "Show processing orders", value: "show processing orders" },
      { label: "Show testing orders", value: "show testing orders" },
      { label: "Show shipped orders", value: "show shipped orders" },
      { label: "Show delivered orders", value: "show delivered orders" },
      { label: "Show cancelled orders", value: "show cancelled orders" },
      { label: "Show recent orders", value: "show recent orders" },
      { label: "Count orders by status", value: "count orders by status" },
    ],
  },
  {
    key: "customer-invoices",
    label: "Customer Invoices",
    endpoint: "customer-invoices/chatbot",
    questions: [
      { label: "Show all invoices", value: "show all invoices" },
      { label: "Show recent invoices", value: "show recent invoices" },
      { label: "Count total invoices", value: "count total invoices" },
      { label: "Show high value invoices", value: "show high value invoices" },
      { label: "Show invoices this month", value: "show invoices this month" },
      { label: "Total invoice value", value: "total invoice value" },
      { label: "Show monthly invoice trend", value: "show monthly invoice trend" },
    ],
  },
  {
    key: "customers",
    label: "Customers",
    endpoint: "customers/chatbot",
    questions: [
      { label: "Show all customers", value: "show all customers" },
      { label: "Show recent customers", value: "show recent customers" },
      { label: "Count total customers", value: "count total customers" },
      { label: "Show top customers by orders", value: "show top customers by orders" },
      { label: "Show customers with no orders", value: "show customers with no orders" },
      { label: "Show customers by city", value: "show customers by city" },
      { label: "Show customer order breakdown", value: "show customer order breakdown" },
    ],
  },
  {
    key: "inventory",
    label: "Inventory",
    endpoint: "inventory/chatbot",
    questions: [
      { label: "Show all products", value: "show all products" },
      { label: "Show low stock products", value: "show low stock products" },
      { label: "Show out of stock products", value: "show out of stock products" },
      { label: "Count total products", value: "count total products" },
      { label: "Show top products by stock", value: "show top products by stock" },
      { label: "Show products with holds", value: "show products with holds" },
      { label: "Show inventory value", value: "show inventory value" },
    ],
  },
  {
    key: "stock",
    label: "Raw Materials",
    endpoint: "stock/chatbot",
    questions: [
      { label: "Show all raw materials", value: "show all raw materials" },
      { label: "Show low raw materials", value: "show low raw materials" },
      { label: "Show out of stock raw materials", value: "show out of stock raw materials" },
      { label: "Count total raw materials", value: "count total raw materials" },
      { label: "Show materials by location", value: "show materials by location" },
      { label: "Show most needed materials", value: "show most needed materials" },
      { label: "Show raw material value", value: "show raw material value" },
    ],
  },
  {
    key: "bom",
    label: "BOM",
    endpoint: "bom/chatbot",
    questions: [
      { label: "Show all BOMs", value: "show all boms" },
      { label: "Count total BOMs", value: "count total boms" },
      { label: "Show most complex BOMs", value: "show most complex boms" },
      { label: "Show recently updated BOMs", value: "show recently updated boms" },
      { label: "Show high value BOMs", value: "show high value boms" },
    ],
  },
  {
    key: "work-orders",
    label: "Work Orders",
    endpoint: null,
    questions: [],
  },
];
