export const ROLES = {
  ADMIN: "admin",
  CUSTOMER: "customer",
  SALES: "sales",
  DESIGN: "design",
  PRODUCTION: "production",
  STORE: "store",
  DISPATCH: "dispatch",
  ACCOUNTS: "accounts",
  // Compage
  EMPLOYEE: "employee",
  HR: "hr",
  // Intute
  IA_EMPLOYEE: "ia_employee",
  IA_HR: "ia_hr",
};

export const DASHBOARD_ROUTES = {
  [ROLES.ADMIN]: "/admin-dashboard",
  [ROLES.SALES]: "/sales-dashboard",
  [ROLES.DESIGN]: "/design-dashboard",
  [ROLES.PRODUCTION]: "/production-dashboard",
  [ROLES.STORE]: "/store-dashboard",
  [ROLES.DISPATCH]: "/dispatch-dashboard",
  [ROLES.ACCOUNTS]: "/accounts-dashboard",
  [ROLES.CUSTOMER]: "/customer-dashboard",
  // Compage
  [ROLES.EMPLOYEE]: "/employee-dashboard",
  [ROLES.HR]: "/hr-dashboard",
  // Intute
  [ROLES.IA_EMPLOYEE]: "/ia-employee-dashboard",
  [ROLES.IA_HR]: "/ia-hr-dashboard",
};

export const allowedPathsByRole = {
  [ROLES.ADMIN]: [
    "/admin-dashboard",
    "/orders",
    "/queries",
    "/customer-list",
    "/inventory",
    "/stock",
    "/price-list",
    "/pdi",
    "/customer-invoices",
    "/part-drawings",
    "/part-drawings/finished",
    "/part-drawings/raw",
    "/enquiries",
    "/dispatch-tracking",
    "/purchase-invoices",
    "/bom",
    "/edit-profile",
    "/problems",
    "/work-orders",
    "/select-component/:orderId/:action",
    "/processes/:orderId",
    "/processes/non-motor/:orderId",
    "/quotation",
    "/proforma",
    "/part-creation",
    "/delivery-challan",
    "/motor-recipes",
  ],
  [ROLES.CUSTOMER]: [
    "/customer-dashboard",
    "/customer-orders",
    "/customer-queries",
    "/edit-profile",
  ],
  [ROLES.SALES]: [
    "/sales-dashboard",
    "/orders",
    "/sales-inventory",
    "/sales-queries",
    "/stock",
    "/price-list",
    "/customer-invoices",
    "/sales/enquiries",
    "/dispatch-tracking",
    "/edit-profile",
    "/sales/quotations",
    "/proforma",
  ],
  [ROLES.DESIGN]: [
    "/design-dashboard",
    "/queries",
    "/design/enquiries",
    "/pdi",
    "/part-drawings/finished",
    "/part-drawings/raw",
    "/bom",
    "/edit-profile",
    "/design/part-creation",
    "/motor-recipes",           // ← added
  ],
  [ROLES.PRODUCTION]: [
    "/production-dashboard",
    "/production-orders",
    "/orders",
    "/production-queries",
    "/production-stock",
    "/inventory",
    "/production-part-drawings",
    "/production-part-drawings-raw",
    "/production-pdi",
    "/production-bom-unpriced",
    "/bom",
    "/edit-profile",
    "/production-inventory",
    "/work-orders",
    "/select-component/:orderId/:action",
    "/processes/:orderId",
    "/processes/non-motor/:orderId",
    "/motor-recipes",           // ← added
  ],
  [ROLES.STORE]: [
    "/store-dashboard",
    "/inventory",
    "/stock",
    "/bom",
    "/edit-profile",
  ],
  [ROLES.DISPATCH]: [
    "/dispatch-dashboard",
    "/queries",
    "/stock",
    "/pdi",
    "/dispatch-tracking",
    "/edit-profile",
  ],
  [ROLES.ACCOUNTS]: [
    "/accounts-dashboard",
    "/orders",
    "/customer-invoices",
    "/dispatch-tracking",
    "/purchase-invoices",
    "/edit-profile",
  ],

  // ── Compage ──────────────────────────────────────────────
  [ROLES.EMPLOYEE]: [
    "/employee-dashboard",
    "/attendance-history",
    "/my-activities",
    "/edit-profile",
  ],
  [ROLES.HR]: [
    "/hr-dashboard",
    "/attendance-summary",
    "/hr-activities",
    "/employee-details",
    "/edit-profile",
  ],

  // ── Intute ───────────────────────────────────────────────
  [ROLES.IA_EMPLOYEE]: [
    "/ia-employee-dashboard",
    "/ia-attendance-history",
    "/activities",
    "/ia-orders",
    "/edit-profile",
  ],
  [ROLES.IA_HR]: [
    "/ia-hr-dashboard",
    "/ia-attendance-summary",
    "/activities",
    "/ia-orders",
    "/hr-payslips",
    "/edit-profile",
  ],
};